---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/content/blog
  label: Articles
  create: all
  match: "**/*.md"
  new_doc_ext: md
upload_dir: src/images/blog
public_path: "/src/images/blog"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install --frozen-lockfile
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn run develop
